name: AB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed" >> files.log 2>&1
            echo "Count Tab in files: `grep -P '\t' $file | wc -l`" >> files.log 2>&1 
          done
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: files.log
